- name: mongodb
  hosts: telecmi
  sudo: True
  tasks:
    - name: mongodb key
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10 state=present

    - name: Add MongoDB repository
      apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present 
 
    - name: install mongodb
      apt: pkg=mongodb-org update_cache=yes state=present
 
    - name: start mongodb
      service: name=mongod state=started 
      
