- name: ruby
  hosts: telecmi
  sudo: True
  tasks:
    - name: install curl
      apt: name=curl state=present

    - name: rvm using curl
      shell: https://get.rvm.io | bash -s stable
      
    - name: install ruby dependencies 
      action: apt pkg={{item}} state=installed
      with_items:
        - automake
        - bison
        - autoconf
        - libreadline6
        - libreadline6-dev
        - libssl-dev
        - gawk
        - zlib1g-dev
        - libyaml-dev
        - libsqlite3-dev
        - libxml2-dev
        - libxslt1-dev
       
    - name: install ruby
      apt: name=ruby update_cache=yes state=present

    - name: install rails
      apt: name=rails state=present

